### ISSUE TITLE
notifications break

### ISSUE THREAD

**Issue by mkounkel** [r-xue/ads2bibdesk#1]
Hi,

I'm running python 3.6, on 10.12. The code works well so far, with one exception - notify module results in error.

    objc.lookUpClass('NSUserNotificationCenter').\
AttributeError: 'NoneType' object has no attribute 'scheduleNotification_'

During handling of the above exception, another exception occurred:

    growl_notify(title, desc, sticky)
NameError: name 'growl_notify' is not defined

Commenting out the last line has fixed it, resulting in a successful download.

**Comment by Morisset** [comment]
Same issue for me on OSX 10.10, python 3.7.2.
Encapsulating the growl_notify in a try does the job.

**Comment by r-xue** [comment]
Thank both of you. I have merged the PR.
