### ISSUE TITLE
Suggestion - Rename PDF files by first author and year

### ISSUE THREAD

**Issue by beastfromthedeep** [r-xue/ads2bibdesk#13]
Dear r-xue,

This is an enhancement suggestion.

Is it possible for ads2bibdesk to name the downloaded PDFs using the first author name and the date.  So your paper this year might be named Xue2020.pdf.  And your second paper this year could be Xue2020b.pdf (etc etc).

Currently the papers that ads2bibdesk downloads for me have names like tmpav9l1brw.pdf

Kind regards

**Comment by r-xue** [comment]
The PDF filenames in a **BibDesk** library are largely determined by your preference setting (see my screenshots).

**ads2bibdesk** first downloads a PDF under a random filename in /tmp (if I recall correctly). Then **BibDesk** processes that file, following its "auto file" setting. You can pick your preferred PDF naming rule and file paths etc. there. 

Is it possible that you turn off "File papers automatically"? I guess this may preserve the original random name from **ads2bibdesk**.

`Preference`
![prefs1](https://user-images.githubusercontent.com/3730692/81197130-8a2f4f00-8f85-11ea-9826-59146cc3cdbe.jpg)
`Autofile`
![prefs2](https://user-images.githubusercontent.com/3730692/81197139-8b607c00-8f85-11ea-8400-efb8873e7a92.jpg)
`Advanced`
![prefs3](https://user-images.githubusercontent.com/3730692/81197136-8ac7e580-8f85-11ea-8f4e-ee91cb18f9df.jpg)

**Comment by beastfromthedeep** [comment]
You are right.  OMG, I feel like a total n00b.

Thanks very much for the advice.  It has been filed wrong ever since I got a new computer.  I didn't even think that this was a bibdesk issue as I only ever file using ads2bibdesk.
