### ISSUE TITLE
Problems running on Catalina

### ISSUE THREAD

**Issue by bryanmiller** [r-xue/ads2bibdesk#15]
I recently updated from macOS High Sierra to Catalina. ads2bibdesk was working fine on High Sierra but now gives errors (see below). I'm trying to run this in python 3.7.9 managed with conda. Does this need a different version of ImageMagick? Are there other tricks or suggestions? Thanks.
[ads2bibdesk_errors.txt](https://github.com/r-xue/ads2bibdesk/files/6029735/ads2bibdesk_errors.txt)

**Comment by bryanmiller** [comment]
Also, I'm now using Bibdesk 1.8.

**Comment by bryanmiller** [comment]
Working now..

**Comment by r-xue** [comment]
okay. glad it worked.
