### ISSUE TITLE
App problem finding bibcodes

### ISSUE THREAD

**Issue by mmaclow** [r-xue/ads2bibdesk#17]
I am getting the following error message in the log, and nothing happens.

2021-06-17 11:48:14 ads2bibdesk.ads2bibdesk.main     [INFO]   : Starting ADS to BibDesk
2021-06-17 11:48:25 ads2bibdesk.ads2bibdesk.process_token [INFO]   : Found Zero or Multiple ADS antries for [valid API key]
2021-06-17 11:48:25 ads2bibdesk.ads2bibdesk.process_token [INFO]   : No update in BibDesk

I just created the .ads directory (so no pre-existing files present) and added my brand new API key from ADS to ads2bibdesk.cfg, but still got this error.

**Comment by r-xue** [comment]
It sounds like the query found a non-single match (and the query request did work, otherwise, an API response error will be returned):

Could you try `ads2bibdesk -d "your_article_identifier"`? The debug log might show the exact "Matching Number" returned from the ads server: zero or something else?

**Comment by mmaclow** [comment]
That command loaded the requested article successfully!  So, could it be a problem with the app?

**Comment by r-xue** [comment]
This might be the known issue related to the macOS privacy feature (see README.rst and #8), which could prevent one app to access text from another app. 
I assume you're using Catalina or Big Sur?

**Comment by mmaclow** [comment]
Yep, Catalina.  I was trying to use the app to access text highlighted in Google Chrome, though, which is listed as OK in the referenced issue.  Well, I guess I can live with the CLI, so let me not take up any more of your time.
