### ISSUE TITLE
Found Zero or Multiple ADS antries for ...

### ISSUE THREAD

**Issue by foice** [r-xue/ads2bibdesk#21]
I am trying to use ads2bibdesk from the commandline. It worked fine until maybe a week ago when I used it last time. I have not used this for a week and have not updated the OS or python.

Now I get this "zero or multiple entries" error for basically any arXiv number I feed ...
```
Starting ADS to BibDesk
Found Zero or Multiple ADS antries for 2209.09905
```
am I the only one seeing this problem?

**Comment by foice** [comment]
It may also be ADS being down or faulty?
`https://ui.adsabs.harvard.edu/search/q=arxiv%3A2209.09905&sort=date%20desc%2C%20bibcode%20desc&p_=0`
returns indeed zero abstracts ...

**Comment by r-xue** [comment]
From my experience, there could be a one/two-day delay before ADS ingests new entries from arXiv. The article you mentioned is relatively new (just posted on Thu, 09/22). It seems to show up now. 

Have you tried again?

**Comment by foice** [comment]
ADS feedback said they had a problem with arXiv for a couple of days, and it was on the way to be fixed. Now it works fine.

**Comment by r-xue** [comment]
Sounds good! Then I will close this issue since it's out of the scope here.
